### ISSUE TITLE
Adding Stocks Error

### ISSUE THREAD

**Issue by 1ultimat3** [fho/stockanalyser#2]
When adding stocks I receive the following error: 

INFO:__main__:Adding Stock PSM.DE
INFO:stockanalyser.analysis.levermann:Creating Levermann Analysis for PSM.DE
Traceback (most recent call last):
  File "./analyser", line 248, in <module>
    configure_argparse()
  File "./analyser", line 65, in configure_argparse
    args.func(args)
  File "./analyser", line 206, in add
    l.evaluate()
  File "/home/mate/stockanalyser/stockanalyser/analysis/levermann.py", line 216, in evaluate
    self.eval_quarterly_figures_reaction()
  File "/home/mate/stockanalyser/stockanalyser/analysis/levermann.py", line 396, in eval_quarterly_figures_reaction
    qf_prev_day = prev_weekday(self.stock.last_quarterly_figures_release_date())
  File "/home/mate/stockanalyser/stockanalyser/analysis/levermann.py", line 28, in prev_weekday
    return adate - timedelta(days=_offsets[adate.weekday()])
AttributeError: 'NoneType' object has no attribute 'weekday'

**Comment by fho** [comment]
try again please with the current master branch :-)

**Comment by mateuszk87** [comment]
Hi, thanks for the great support :)
I think there is a bug in the last_quarterly_figures_release_date function `return self.last_quarterly_figures_date,` it does not work for me, is that correct? :)
```
    def last_quarterly_figures_release_date(self):
        self.quarterly_figure_dates.sort()
        today = datetime.date.today()
        for d in reversed(self.quarterly_figure_dates):
            if d <= today:
                return d
        return self.last_quarterly_figures_date
```

**Comment by 1ultimat3** [comment]
works now
